services:
  agent:
    image: portainer/agent
    container_name: portainer_agent
    restart: unless-stopped
    networks:
      - public_hosting
    ports:
      - '9001:9001'
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/docker/volumes:/var/lib/docker/volumes'

networks:
  public_hosting:
    external: true
