services:
  portainer-ce:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    networks:
      - public_hosting
    ports:
      - '8000:8000'
      - '9000:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer_data:/data'

networks:
  public_hosting:
    external: true