services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-npm
    restart: unless-stopped
    networks:
      - public_hosting
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'

networks:
  public_hosting:
    external: true